# Generated by Django 5.1.3 on 2024-11-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('s3_encrypted_key', models.CharField(default='', max_length=255)),
                ('s3_metadata_key', models.CharField(default='', max_length=255)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
