# Generated by Django 5.1.3 on 2024-11-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0004_document_exporter_document_original_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='s3_encrypted_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='s3_metadata_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='document',
        ),
        migrations.RemoveField(
            model_name='request',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='updated_at',
        ),
    ]
