# Generated by Django 5.1.3 on 2024-11-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='time',
        ),
    ]
