# Generated by Django 5.1.3 on 2024-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Exporter'), (3, 'Shipper')], default=2, verbose_name='User Type'),
        ),
    ]
