# Generated by Django 5.1.3 on 2024-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Exporter'), (3, 'Shipper'), (4, 'Actor')], default=2, verbose_name='User Type'),
        ),
    ]
